mysite/myapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about$', views.about, name='about'),
    url(r'^detail/(?P<course_no>\d+)$', views.detail, name='detail'),
    url(r'^topics$', views.topics, name='topics'),
    url(r'^addtopic$', views.addtopic, name='addtopic'),
    url(r'^topics/(?P<topic_id>\d+)$', views.topicdetail, name='topicdetail'),
    url(r'^mycourses$', views.mycourses, name='mycourses'),

    url(r'register$', views.register, name='register'),
    url(r'login$', views.user_login, name='login'),
    url(r'logout', views.user_logout, name='logout')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^myapp/', include('myapp.urls', namespace = 'myapp')),
    url(r'^admin/', admin.site.urls),
]

mysite/myapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Author(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    birthdate = models.DateField()
    city = models.CharField(null = True,max_length=100, blank=True )
    def __str__(self):
        return self.firstname + " " + self.lastname

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    in_stock = models.BooleanField(default=True)
    numpages = models.IntegerField(null = True, validators=[MinValueValidator(50), MaxValueValidator(1000)])
    def __str__(self):
        return self.title

class Student(User):
    PROVINCE_CHOICES = (
            ('AB','Alberta'), # First value is stored in db, the second is descriptive
            ('MB', 'Manitoba'),
            ('ON', 'Ontario'),
            ('QC', 'Quebec'),
            )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    age = models.IntegerField()
    def __str__(self):
        return self.first_name + " " + self.last_name

class Course(models.Model):
    course_no = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    textbook = models.ForeignKey(Book)
    students = models.ManyToManyField(Student)
    def __str__(self):
        return self.title
class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afternoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age =models.IntegerField(default=20)
    def __str__(self):
        return self.subject

mysite/myapp/forms.py
from django import forms
from myapp.models import Topic, Student

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['subject', 'intro_course', 'time', 'avg_age']
    time = forms.ChoiceField(widget=forms.RadioSelect, label='Preferred Time', choices=Topic.TIME_CHOICES)
    avg_age = forms.CharField(max_length=3, label='What is your age?')
    intro_course = forms.BooleanField(label='This should be an introductory level course')

class InterestForm(forms.Form):
    interested =  forms.ChoiceField(widget=forms.RadioSelect, choices=(('1','yes'),('2','no')))
    age = forms.IntegerField(initial='20')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='Additional Comments')

class RegisterForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['username', 'first_name', 'last_name', 'password', 'email', 'age', 'address', 'city', 'province']
        widgets = { 'password': forms.PasswordInput() }

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)

mysite/myapp/templates/myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from myapp.models import Author, Book, Course

# Create your views here.
def index(request):
    courselist = Course.objects.all().order_by('title')[:10]
    return render(request, 'myapp/index.html', {'courselist': courselist})

def about(request):
    return render(request, 'myapp/about.html')

def detail(request, course_no):
    response = HttpResponse()
    #course = getCourse.objects.get(pk=course_no) #basic
    course = get_object_or_404(Course, pk=course_no)
    return render(request, 'myapp/detail.html',{'course': course})

mysite/myapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from myapp.models import Author, Book, Course, Topic, Student
from myapp.forms import TopicForm, InterestForm, RegisterForm, LoginForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    courselist = Course.objects.all().order_by('title')[:10]
    return render(request, 'myapp/index.html', {'courselist': courselist})

def about(request):
    return render(request, 'myapp/about.html')

def detail(request, course_no):
    response = HttpResponse()
    #course = getCourse.objects.get(pk=course_no) #basic
    course = get_object_or_404(Course, pk=course_no)
    return render(request, 'myapp/detail.html',{'course': course})
def topics(request):
    topiclist = Topic.objects.all()[:10]
    return render(request, 'myapp/topics.html', {'topiclist': topiclist})

def addtopic(request):
    topiclist = Topic.objects.all()
    if request.method=='POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses=1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form=TopicForm()
    return render(request, 'myapp/addtopic.html', {'form':form, 'topiclist':topiclist})

def topicdetail(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    if request.method=='POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['interested'] == '1':
                topic.num_responses +=1
                topic.avg_age = (topic.avg_age + form.cleaned_data['age'])/(topic.num_responses)
                topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form = InterestForm()
    return render(request, 'myapp/topicdetail.html', {'form':form, 'topic':topic})

def register(request):
    if(request.method=='POST'):
        form = RegisterForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.set_password(form.cleaned_data['password'])
            instance.is_active = True
            instance.is_staff = True
            instance.is_superuser = True
            instance.save()
            return HttpResponseRedirect(reverse('myapp:index'))
    else:
        form = RegisterForm()
        return render(request, 'myapp/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        form = LoginForm()
        return render(request, 'myapp/login.html', {'form':form})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))

def mycourses(request):
    if request.user.is_authenticated:
        # courses = Student.objects.get(username=request.user.username).course_set.all()
        courses = get_object_or_404(Student, username=request.user.username).course_set.all()
        return render(request, 'myapp/mycourse.html', {'courses':courses})
    else:
        return render(request, 'myapp/mycourse.html')

mysite/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
	hello Jianye Liu
{% endblock %}
{% block body_block %}
	<p>this is the about page</p>
{% endblock %}

mysite/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>About page</title>
</head>
<body>
	<p>this is the about page</p>
	<p><a href="/myapp/">home page (hardcoded)</a></p>
	<p><a href="{% url 'myapp:index' %}">home page (url namespacing)</a></p>
</body>
</html>

mysite/myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
	<form action="{% url 'myapp:addtopic' %}" method="POST">
		{% csrf_token %}
		{{ form.as_ul }}
		<input type="submit" value="Submit"/>
	</form>
{% endblock %}

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="course application">
		<meta name="author" content="Jianye Liu">
		{% load staticfiles %}
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Custom styles for this template -->
		<link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
		<title>Course Listing APP - {% block title %}Welcome!{% endblock %}</title>
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Django myapp</a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href = "{% url 'myapp:index' %}">Home Page</a></li>
						<li><a href ="{% url 'myapp:topics' %}">Topics</a></li>
						{% if request.user.is_authenticated %}
						<li><a href="{% url 'myapp:mycourses' %}">My Courses</a></li>
						{% endif %}
						<li><a href="{% url 'myapp:about' %}">About</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% if request.user.is_authenticated %}
						<li><a href="#">Hello {{ request.user.first_name }}</a></li>
						<li><a href="{% url 'myapp:logout' %}">Logout</a></li>
						{% else %}
						<li><a href="{% url 'myapp:login' %}">Login</a></li>
						<li><a href="{% url 'myapp:register' %}">Register</a></li>
						{% endif %}
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">
			{% block body_block %}*** {% endblock %}
		</div>
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	</body>
</html>

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
	hello Jianye Liu
{% endblock %}
{% block body_block %}
	{% if course %}
	<h2>detail of Course</h2>
	<ol>
		<li> Title: {{ course.title }} </li>
		<li> Course Number: {{ course.course_no }} </li>
		<li> Course textbook: {{ course.textbook.title }} </li>
	</ol>
	{% else %}
	<strong>There are no available course!</strong>
	{% endif %}
{% endblock %}

mysite/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<title>Course Listing APP</title>
	</head>
	<body>
		{% if course %}
		<h2>detail of Course</h2>
		<ol>
			<li> Title: {{ course.title }} </li>
			<li> Course Number: {{ course.course_no }} </li>
			<li> Course textbook: {{ course.textbook.title }} </li>
		</ol>
		{% else %}
		<strong>There are no available course!</strong>
		{% endif %}
		<p><a href="{% url 'myapp:index' %}">home page</a></p>
	</body>
</html>

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
hello Jianye Liu
{% endblock %}
{% block body_block %}
{% if courselist %}
<h2 class="sub-header">List of Courses</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Course ID</th>
				<th>Title</th>
				<th>TextBook</th>
				<th>Detail</th>
			</tr>
		</thead>
		<tbody>
			{% for course  in courselist %}
			<tr>
				<th> {{ course.course_no }} </th>
				<th> {{ course.title }} </th>
				<th> {{ course.textbook }} </th>
				<th><a href="{% url 'myapp:detail' course.course_no %}">more</a></th>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
<strong>There are no available courses!</strong>
{% endif %}
{% endblock %}

mysite/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8">
		<title>Course Listing APP</title>
	</head>
	<body>
		{% if courselist %}
		<h2>List of Courses</h2>
		<ol>
			{% for course  in courselist %}
			<li> <a href="{% url 'myapp:detail' course.course_no %}">{{ course.title }} - {{ course.course_no }}</a> </li>
			{% endfor %}
		</ol>
		{% else %}
		<strong>There are no available courses!</strong>
		{% endif %}
		<p><a href="{% url 'myapp:about' %}">About page</a></p>
	</body>
</html>

mysite/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <form method="post" action="{% url 'myapp:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="submit">
    </form>
{% endblock %}

mysite/myapp/templates/myapp/mycourse.html
{% extends 'myapp/base.html' %}
{% block body_block %}
{% if request.user.is_authenticated and courses %}
<h2 class="sub-header">List of My Courses</h2>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Course ID</th>
				<th>Title</th>
				<th>TextBook</th>
				<th>Detail</th>
			</tr>
		</thead>
		<tbody>
			{% for course  in courses %}
			<tr>
				<th> {{ course.course_no }} </th>
				<th> {{ course.title }} </th>
				<th> {{ course.textbook }} </th>
				<th><a href="{% url 'myapp:detail' course.course_no %}">more</a></th>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
<strong>You are not a student!</strong>
{% endif %}
{% endblock %}

mysite/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <form method="post" action="{% url 'myapp:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" name="submit" value="submit"></p>
    </form>
{% endblock %}

mysite/myapp/templates/myapp/topicdetail.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
	hello Jianye Liu
{% endblock %}
{% block body_block %}
	{% if topic %}
	<h2>detail of Topic</h2>
	<ol>
		<li> subject: {{ topic.subject }} </li>
		<li> intro_course : {{ topic.intro_course }} </li>
		<li> num responses: {{ topic.num_responses }} </li>
		<li> average age {{ topic.avg_age }} </li>
	</ol>
	{% else %}
	<strong>There are no available course!</strong>
	{% endif %}
	<hr/>
	<form action="{% url 'myapp:topicdetail' topic.id %}" method="POST">
		{% csrf_token %}
		{{ form.as_ul }}
		<input type="submit" value="Submit" />
	</form>
{% endblock %}

mysite/myapp/templates/myapp/topics.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
Jianye Liu
{% endblock %}
{% block body_block %}
{% if topiclist %}
<h2 class="sub-header">All Topics</h2>

<div class="bpx azo">
	<div class="input-group headsearch">
		<span class="input-group-addon">search</span>
		<input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
	</div>
	<div class="bpy">
		<div class="pz">
			<a href="{% url 'myapp:addtopic' %}" role="button" class="btn btn-primary">
				<span class="glyphicon glyphicon-plus">Add New Topic</span>
			</a>
		</div>
	</div>
</div>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Topic ID</th>
				<th>Subject</th>
				<th>Time</th>
				<th>Introduction Course</th>
				<th>Detail</th>
			</tr>
		</thead>
		<tbody>
			{% for topic  in topiclist %}
			<tr>
				<th> {{ topic.id }} </th>
				<th> {{ topic.subject }} </th>
				<th> {{ topic.time }} </th>
				<th> {{ topic.intro_course }} </th>
				<th><a href="{% url 'myapp:topicdetail' topic.id %}">more</a></th>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% else %}
<strong>There are no available topics!</strong>
{% endif %}
{% endblock %}